[package]
name = "rust_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
pingora = { version = "0.4", features = ["lb"] } # 2025-1-18での最新バージョン
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
env_logger = "0.11"
http = "1"